version: '3.4'

services:
  app:
    image: api:app
    build: .
    volumes:
      - ./:/app
    ports:
      - 80:80

  cli:
    image: api:cli
    build:
      context: .
      target: cli
    volumes:
      - ./:/app

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: api
    ports:
      - 3306:3306
